#!/usr/bin/env python3
"""
Author : dannyk <dannyk@localhost>
Date   : 2023-02-21
Purpose: Rock the Casbah
"""

import argparse
from ast import main


# --------------------------------------------------
def get_args():
    """Get command-line arguments"""

    parser = argparse.ArgumentParser(
        description='Rock the Casbah',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('positional',
                        metavar='str',
                        help='A positional argument')

    return parser.parse_args()

#----------------------------------------------------
def main():
    """Make a jazz noise here"""

    args = get_args()
    jumper = {'1': '9', '2': '8', '3':'7', '4':'6','5':'0',
              '6': '4', '7': '3', '8': '2', '9': '1', '0': '5'}

    #method 4: list comprehension
    print(''.join([jumper.get(char, char) for char in args.text]))



# ---------------------------------------------
if __name__ == '__main__':
    main()
    